steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - "--no-cache"
      - "-t"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/ice-cream-man/ice-cream-man-api:latest"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - "us-central1-docker.pkg.dev/$PROJECT_ID/ice-cream-man/ice-cream-man-api:latest"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ice-cream-man-api
      - "--image=us-central1-docker.pkg.dev/$PROJECT_ID/ice-cream-man/ice-cream-man-api:latest"
      - "--region=us-central1"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--cpu=1"
      - "--memory=512Mi"
      - "--min-instances=0"
      - "--max-instances=2"
      - "--set-env-vars=NODE_ENV=production"
      - "--set-secrets=DATABASE_URL=databases/icecreamman:latest,JWT_SECRET=icm-jwt-secret:latest"
      - "--service-account=play-console-service-account-f@$PROJECT_ID.iam.gserviceaccount.com"

images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/ice-cream-man/ice-cream-man-api:latest"
